[phases.setup]
nixPkgs = ['...', 'nginx']

[phases.build]
cmds = [
  'composer install --no-dev --optimize-autoloader',
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache'
]

[start]
cmd = 'bash start.sh'
